# Generated by Django 3.1.3 on 2021-02-07 12:54

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('testapp', '0002_movies'),
    ]

    operations = [
        migrations.CreateModel(
            name='BookMovie',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('booking_date', models.DateField(default=django.utils.timezone.now)),
                ('movie', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='testapp.movies')),
                ('user', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
