# Generated by Django 3.1.3 on 2021-02-12 12:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('testapp', '0004_bookmovie_reviews'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bookmovie',
            name='reviews',
        ),
    ]
